export const BANCO_PREGUNTAS = {
  "organica": [
    { "id": 1, "texto": "¿Ha aplicado herbicidas o fertilizantes químicos en sus parcelas durante los últimos 3 años?", "tipo": "boolean", "meta": false, "recomendacion": "La normativa exige un periodo de 36 meses libre de químicos. Se debe sustituir el uso de glifosato por control manual o mecánico y utilizar nutrición basada en compostas certificadas." },
    { "id": 2, "texto": "¿Cuenta con barreras vivas o hileras de árboles para evitar la contaminación de parcelas vecinas?", "tipo": "boolean", "meta": true, "recomendacion": "Es obligatorio establecer cortinas vegetales en los linderos para proteger el cultivo de químicos aplicados en fincas colindantes." },
    { "id": 3, "texto": "¿Mantiene un registro diario de las actividades y productos aplicados en la finca?", "tipo": "boolean", "meta": true, "recomendacion": "La documentación es indispensable para la certificación. Debe registrar cada aplicación de abono, labores de limpieza y fechas de cosecha para asegurar la trazabilidad." },
   { "id": 4, "texto": "¿Qué porcentaje de sus plantas o semillas provienen de fuentes con certificado orgánico?", "tipo": "percentage", "meta": 80, "recomendacion": "El estándar exige material vegetativo orgánico. Si adquiere plantas, debe solicitar el certificado del vivero; si son propias, la planta madre debe estar libre de químicos." },
    { "id": 5, "texto": "Nivel de aislamiento de su bodega para el almacenamiento de insumos (1-10):", "tipo": "scale", "meta": 7, "recomendacion": "La bodega debe ser exclusiva para insumos permitidos y estar separada de herramientas, aceites o combustibles para evitar contaminaciones accidentales." },
    { "id": 6, "texto": "¿Realiza análisis de suelo anualmente para programar su plan de fertilización?", "tipo": "boolean", "meta": true, "recomendacion": "La agricultura orgánica depende de la salud del suelo. Un análisis permite aplicar solo los nutrientes necesarios y evitar la sobre-fertilización." },
    { "id": 7, "texto": "Distancia mínima (metros) entre sus cultivos y depósitos de residuos o basura:", "tipo": "number", "meta": 15, "recomendacion": "La inocuidad es fundamental. El café debe estar a una distancia mínima de 15 metros de focas sépticas o basureros para evitar riesgos biológicos." }
  ],

  "comercio_justo": [
    { "id": 8, "texto": "¿Garantiza que no exista trabajo infantil o menores de 15 años laborando en la finca?", "tipo": "boolean", "meta": true, "recomendacion": "Fairtrade tiene tolerancia cero al trabajo infantil. Se debe verificar la edad y asegurar que los hijos de los trabajadores asistan a la escuela." },
    { "id": 9, "texto": "¿El salario que paga a sus colaboradores cumple con el mínimo legal vigente?", "tipo": "boolean", "meta": true, "recomendacion": "El Comercio Justo promueve condiciones dignas. Es necesario mantener registros que comprueben el pago del salario mínimo y el respeto a la jornada laboral legal." },
    { "id": 10, "texto": "¿Tienen las mujeres las mismas oportunidades de trabajo y pago que los hombres?", "tipo": "boolean", "meta": true, "recomendacion": "Se deben implementar políticas de equidad de género, asegurando igualdad salarial por la misma labor y participación en la toma de decisiones." },
    { "id": 11, "texto": "Porcentaje de asistencia de los socios a las asambleas generales:", "tipo": "percentage", "meta": 70, "recomendacion": "La democracia interna es la base de la organización. Fomente la participación de al menos el 70% de los socios y mantenga actas firmadas como evidencia." },
    { "id": 12, "texto": "¿Provee equipo de seguridad (botas, guantes) a sus trabajadores de campo?", "tipo": "boolean", "meta": true, "recomendacion": "La seguridad laboral es obligatoria. Se debe invertir en equipos de protección y botiquines de primeros auxilios en las áreas de trabajo." },
    { "id": 13, "texto": "¿Cuántas capacitaciones técnicas o de derechos han recibido los socios en el año?", "tipo": "number", "meta": 3, "recomendacion": "Se requieren al menos 3 capacitaciones anuales sobre calidad de café, manejo financiero o derechos laborales para fortalecer la organización." },
    { "id": 14, "texto": "¿Cuenta con un comité para vigilar el uso transparente del premio o prima Fairtrade?", "tipo": "boolean", "meta": true, "recomendacion": "Debe existir un comité que decida democráticamente la inversión del dinero extra en proyectos comunitarios como salud o infraestructura." }
  ],

  "rainforest_utz": [
    { "id": 15, "texto": "¿Ha evitado la deforestación de áreas de bosque para ampliar sus cafetales después de 2014?", "tipo": "boolean", "meta": false, "recomendacion": "Se prohíbe la conversión de ecosistemas naturales. Si hubo deforestación, se requiere un plan de restauración con especies nativas para mantener el sello." },
   { "id": 16, "texto": "Porcentaje de cobertura de sombra (árboles) en sus parcelas:", "tipo": "percentage", "meta": 40, "recomendacion": "Se recomienda una cobertura del 40%. Integre árboles de sombra diversificados para proteger el suelo y conservar el hábitat de aves." },
    { "id": 17, "texto": "¿Cuenta con sistemas para el tratamiento de aguas residuales del beneficio húmedo?", "tipo": "boolean", "meta": true, "recomendacion": "Verter aguas mieles a los ríos es una falta grave. Es necesario construir filtros biológicos o fosas para tratar el agua antes de su retorno al suelo." },
    { "id": 18, "texto": "¿Cuántas especies de árboles nativos diferentes tiene integradas en su finca?", "tipo": "number", "meta": 5, "recomendacion": "La biodiversidad es clave. Se recomienda contar con al menos 5 especies nativas que funcionen como corredores biológicos." },
    { "id": 19, "texto": "¿Realiza podas técnicas de forma periódica para prevenir plagas como la Roya?", "tipo": "boolean", "meta": true, "recomendacion": "El manejo preventivo mediante podas mejora la ventilación del cultivo y reduce la necesidad de utilizar agroquímicos." },
    { "id": 20, "texto": "Calidad en el manejo de envases vacíos y residuos plásticos (1-10):", "tipo": "scale", "meta": 8, "recomendacion": "Aplique el triple lavado a los envases, perfore el fondo y entréguelos a centros de acopio autorizados. No se permite la quema de plásticos." },
    { "id": 21, "texto": "¿Tiene identificadas las áreas de conservación (ríos o nacimientos de agua)?", "tipo": "boolean", "meta": true, "recomendacion": "Las zonas de protección de agua deben estar marcadas y libres de cualquier actividad agrícola o aplicación de insumos." }
  ],

  "denominacion_origen": [
    { "id": 22, "texto": "¿Se ubica su finca dentro de la zona geográfica protegida por la Denominación de Origen?", "tipo": "boolean", "meta": true, "recomendacion": "Si está fuera del límite legal regional, no podrá utilizar el sello de origen. Verifique su ubicación con los mapas oficiales de la organización." },
    { "id": 23, "texto": "¿Cultiva exclusivamente las variedades de café autorizadas por el Consejo Regulador?", "tipo": "boolean", "meta": true, "recomendacion": "Las Denominaciones protegen variedades tradicionales (Arábigas). Si mezcla con granos de baja calidad o no permitidos, perderá el derecho al sello." },
    { "id": 24, "texto": "Altitud de su parcela registrada en metros sobre el nivel del mar (msnm):", "tipo": "number", "meta": 900, "recomendacion": "Se exige una altitud mínima (generalmente >900 msnm) para garantizar la densidad y acidez típica de la región protegida." },
    { "id": 25, "texto": "¿El proceso de beneficiado y secado se realiza totalmente dentro de la región de origen?", "tipo": "boolean", "meta": true, "recomendacion": "La certificación protege el saber hacer local. Si procesa su café fuera del territorio, se rompe el vínculo con la región y pierde el certificado." },
    { "id": 26, "texto": "Nivel de cumplimiento con el perfil de sabor (taza) típico de su región (1-10):", "tipo": "scale", "meta": 8, "recomendacion": "El café debe cumplir con las notas sensoriales (acidez, cuerpo, aroma) que distinguen a la región. Se sugiere realizar una cata técnica de validación." },
    { "id": 27, "texto": "¿Se encuentra inscrito oficialmente en el registro de productores de su región?", "tipo": "boolean", "meta": true, "recomendacion": "Para comercializar con el sello oficial, debe estar dado de alta ante el consejo regulador y estar abierto a auditorías de trazabilidad." },
    { "id": 28, "texto": "¿Asegura la pureza del lote evitando mezclas con granos de otras regiones?", "tipo": "boolean", "meta": true, "recomendacion": "La reputación regional es vital. Nunca mezcle granos de distintos orígenes; utilice sacos marcados y áreas de almacenamiento exclusivas." }
  ],

  "utz_global": [
    { "id": 29, "texto": "¿Cuenta con un sistema que permita rastrear el café desde la parcela hasta el saco final?", "tipo": "boolean", "meta": true, "recomendacion": "UTZ exige trazabilidad total. Cada lote debe estar identificado para saber exactamente de qué parte de la finca proviene cada saco vendido." },
    { "id": 30, "texto": "¿Ha participado en capacitaciones sobre Buenas Prácticas Agrícolas (BPA) recientemente?", "tipo": "boolean", "meta": true, "recomendacion": "La formación en técnicas de cultivo, poda y fertilización es clave para mejorar la rentabilidad y cumplir con los estándares globales." },
    { "id": 31, "texto": "Rendimiento promedio de su cosecha (Quintales por Hectárea):", "tipo": "number", "meta": 15, "recomendacion": "UTZ busca la eficiencia. Si su rendimiento es bajo, el costo de producción sube. Se sugiere renovar cafetales viejos con variedades más productivas." },
    { "id": 32, "texto": "¿Aplica un manejo adecuado de las aguas residuales (aguas mieles) del beneficio?", "tipo": "boolean", "meta": true, "recomendacion": "La higiene del agua es prioridad. Debe implementar trampas de pulpa y sistemas de filtrado para evitar la contaminación de fuentes hídricas." },
    { "id": 33, "texto": "Nivel de higiene y orden en sus instalaciones de secado y patios (1-10):", "tipo": "scale", "meta": 8, "recomendacion": "El café absorbe olores fácilmente. Mantenga las áreas de secado limpias, libres de animales y alejadas de combustibles o basura." },
    { "id": 34, "texto": "¿Dispone de un plan de fertilización basado en los ciclos y necesidades del cultivo?", "tipo": "boolean", "meta": true, "recomendacion": "Debe seguir un calendario que respete las etapas de floración y llenado del grano, optimizando el uso de recursos y evitando desperdicios." },
    { "id": 35, "texto": "¿Lleva un registro de la salud y prevención de accidentes de sus trabajadores?", "tipo": "boolean", "meta": true, "recomendacion": "La responsabilidad laboral es un eje central. Debe documentar que sus trabajadores laboran en condiciones seguras y reciben atención médica si es necesario." }
  ]
};
